[en]
Language = "English (UK)"
language_changed = "Language changed. Hello!"
language_help = "You're speaking English. Do [>lang code<] to set this channel's language:"
command_unknown = "Sorry, [>{command}<] is not a valid command. Do [>help<] for a list."
1 = ">user<, house rules for this game won't let you start in the middle. It's too tactically important to give you for free! :)"
11 = ">user<, you can't take a cell that's already taken."
21 = ">user<, you can't go back to the same grid. Gotta keep movin' and shakin'."
22 = ">user<, that grid is taken."
play_no_args = ">user<, I need a direction with that - or you could run [>random<] if you want..."
play_unknown_direction = ">user<, I don't know any {direction!r}."
play_unknown_error = ">user<, an unknown error occured."
stop_success_solo = "Okay >user<, stopped the game. Hope you had fun!"
stop_success_multi = "Okay >user<, stopped the game. but I hope >opponent< is okay with that!"
status_solo = "No lobby needed - you're welcome to do [>start<] and practice (or play locally)."
status_lobby = "There's a lobby: {noughts} is noughts, and crosses has {time_left:1d} seconds left to do [>start<]"
status_empty = "There's no game in this channel - do [>start<] to start a lobby."
lobby_open = "Okay >user<, you are noughts. Tell crosses to run [>start<] in {time_left} seconds - or type it yourself to practise!"
lobby_game_already_started = "Sorry >user<, one game per channel."
result_draw = "It's a draw. Well played, >user< and >opponent<!"
result_win = "{winner} wins!"
begin = ">user<, which grid do you want to start in?"
inner = ">user<, which cell do you want to place your mark in?"
outer = ">user<, where do you want to send >opponent< to?"
noughts = "Noughts"
crosses = "Crosses"
help = """\
>user<:
Alpha bot for Meta Noughts and Crosses, a tactical variant on Noughts and Crosses. Simple to understand, difficult to master, MNAC will have you playing mind games with the best of them.

One game is allowed per channel. Commands:```
help:     help with a command
tutorial: play a (scripted) tutorial
start:    
stop:     stop game if you're playing
play:     play a move
random:   let fate decide
```"""

help_start = """\
>user<:
Running [>start<] opens a temporary lobby, where the second player can join. The first player can set house rules by including these options in the [>start <options><] command: ```
solo: Single-user (local play)
allowMiddle: allow starting in the middle grid
```"""

[pirate]
Language = "English (Pirate)"
language_changed = "Yarr, ye language be changed."
language_help = "Yarr, ye be speakin' Pirate. Do [>lang code<] to set this ship's tongue:"
command_unknown = "Yarr, I have no idea what {command!r} be."
1 = ">user<, rules o' the house won't let ye start in middle - too much plunder thar to give to ye free!"
11 = ">user<, ye cannae take a space that someone else has plundered."
21 = ">user<, ye cannae go back to the same ocean. Keep on yer toes lad!"
22 = ">user<, that grid is plundered."
play_no_args = ">user<, ye got to tell me where ye want to go - or play the dice and run [>random<]..."
play_unknown_direction = ">user<, no pirate says {direction!r} as a direction."
play_unknown_error = ">user<, Davy Jones must have taken ye game, it be error'd."
stop_success_solo = "Yarr >user<, you quit. Hope ye had fun, ye yellow-belly."
stop_success_multi = "Yarr >user<, ye yellow-belly, I stopped it."
status_solo = "We on private terms 'ere lad, so you can just run [>start<] and practice (or play with your crewmates)."
status_lobby = "{noughts} be noughts, and there's {time_left:1d} seconds fer crosses ta [>start<]"
status_empty = "There be no game in these waters. Run [>start<], lads!"
lobby_open = "Yarr >user<, ye be noughts. Tell crosses ta run [>start<] in {time_left} seconds - or type it yeself to practice."
lobby_game_already_started = "Yer an impatient one, >user<. One game per ship, aye?"
result_draw = "*Well blow me over*, it be a draw. Good game, >user< and >opponent<."
result_win = "Yarr, {winner} wins!"
begin = ">user<, which ocean do ye want to start in?"
inner = ">user<, which space do ye want to plunder?"
outer = ">user<, which ocean do ye want to send >opponent< to?"
noughts = "Noughts"
crosses = "Crosses"

help = """\
>user<:
In-development bot fer Meta Noughts and Crosses, a swashbucklin' kind of Noughts and Crosses all wee pirates remember. Any pirate can learn, but only few can master 'er.

One game is allowed per channel. Commands:```
help:     help with a command
tutorial: play a (scripted) tutorial
start:    
stop:     stop game if you're playing
play:     play a move
random:   let fate decide
```"""

help_start = """\
>user<:
Running [>start<] opens a temporary lobby, where the second player can join. The first player can set house rules by including these options in the [>start <options><] command: ```
solo: Single-user (local play)
allowMiddle: allow starting in the middle grid
```"""

[de]
Language = "Deutch (du)"
language_changed = "Sprach wird geändert. Guten Tag!"
language_help = "Du sprachst Deutsch. Tu [>lang code<], um der Sprach dieser Kannel zu wählen."
command_unknown = "Ich weiß keine Kommand, die {command!r} heißt."
1 = ">user<, die Hausregeln lassen dich nicht ins Mittlel anfangen. Es ist zu wichtig zu kostenlos ausgeben! :)"
11 = ">user<, du kannst nicht eine Zell nehmen, das noch genehmt wird."
21 = ">user<, du kannst nicht zurück nach dem gleichen Grid gehen!"
22 = ">user<, diese Grid wird genehmt."
play_no_args = ">user<, ich brauche eine Richtung damit - oder du kannst [>random<] runnen."
play_unknown_direction = ">user<, ich weiß keine Richtung, die {direction!r} heißt."
play_unknown_error = ">user<, an unknown error occured."
stop_success_solo = "Ok >user<, die Spiel wird gestoppt. Ich hoffe, dass es Spaß macht!"
stop_success_multi = "Ok >user<, die Spiel wird gestoppt, aber ich hoffe, dass >opponent< damit ok ist!"
status_solo = "Keine Lobby wird gebraucht - du kannst [>start<]en und üben (oder mit Freunden spielen)."
status_lobby = "Es gibt eine Lobby: {noughts} ist Kreiz, und Kreuz hat {time_left:1d} Sekonden zu [>start<]en"
status_empty = "Es gibt keine Spiel in diesem Kannel - [>start<], um eine Lobby zu starten."
lobby_open = "Ok >user<, du bist Kreiz. Sagt zu Kreuz, in {time_left} Sekonden zu [>start<]en - oder mach das YOURSELF zu üben!"
lobby_game_already_started = "Entschuldigung >user< - nur ein Spiel pro Kannel."
result_draw = "Es gibt keine Gewinner. Gut gespielt, >user< und >opponent<!"
result_win = "{winner} hat gewonnen!"
begin = ">user<, welche Grid magst du inzustarten?"
inner = ">user<, welche Zell magst du deine Zeich inzustellen?"
outer = ">user<, wo willst >opponent< schicken?"
noughts = "Kreis"
crosses = "Kreuz"

help = """\
Alpha bot für Meta Noughts and Crosses, eine taktische Variante für Kreis und Kreuz. Noughts and Crosses. Simple to understand, difficult to master, MNAC will have you playing mind games with the best of them.

Nur eine Spiel pro Kannel. Commands:```
help:     seh diese Text
tutorial: spiel a (scripted) tutorial
start:    start a new game ([>help start<] for more)
stop:     abruptly stop, if you're a player
play:     (1-9, 'top left', 'west', 'centre', etc)
random:   let fate decide your move
```"""

help_start = """\
>user<:
Running [>start<] opens a temporary lobby, where the second player can join. The first player can set house rules by including these options in the [>start <options><] command: ```
solo: Single-user (local play)
allowMiddle: allow starting in the middle grid
```"""
